#Autogenerated, do not edit.
label bedroom_menu:
    scene bedroom-1
    "Your bed sits, tantalizing. Yet urges are meant to be overcome."
    jump bedroom_menu

label bathroom_menu:
    scene bathroom-1
    "Every morning you curse whoever decided to not put heating in the bathroom."
    "You could put a rug or something to keep your feet off the cold tile, but you don't."
    jump bathroom_menu

label kitchen_menu:
    scene kitchen-1
    "This is your kitchen."
    jump kitchen_menu

label frontdoor_menu:
    scene frontdoor-1
    "This is your front door."
    jump frontdoor_menu

label livingroom_menu:
    scene livingroom-1
    "This is your living room."
    jump livingroom_menu

label exterior_menu:
    scene exterior-1
    "This is your apartment from the outside."
    jump exterior_menu

